### ISSUE TITLE
Issue with Better Sprinklers Plus Mod

### ISSUE THREAD

**Issue by dpraptor** [jamescodesthings/smapi-better-sprinklers#3]
Hi James,
 I installed the Mod, but received this error while the mods were loading:

[Better Sprinklers Plus] This mod failed in the GameLoop.DayStarted event. Technical details:
Failed loading type 'StardewValley.Locations.BuildableGameLocation': TypeLoadException: Could not load type 'StardewValley.Locations.BuildableGameLocation' from assembly 'Stardew Valley, Version=1.6.2.24081, Culture=neutral, PublicKeyToken=null'.
   at BetterSprinklersPlus.Framework.Helpers.LocationHelper.GetAllBuildableLocations()
   at BetterSprinklersPlus.BetterSprinklersPlus.UnwaterAll() in /plugin/BetterSprinklersPlus/BetterSprinklersPlus.cs:line 265
   at BetterSprinklersPlus.BetterSprinklersPlus.RunSprinklers() in /plugin/BetterSprinklersPlus/BetterSprinklersPlus.cs:line 182
   at BetterSprinklersPlus.BetterSprinklersPlus.OnDayStarted(Object sender, DayStartedEventArgs e) in /plugin/BetterSprinklersPlus/BetterSprinklersPlus.cs:line 82
   at StardewModdingAPI.Framework.Events.ManagedEvent`1.Raise(TEventArgs args) in SMAPI\Framework\Events\ManagedEvent.cs:line 101

I just installed Stardew Valley and SNAPI today. I hope you can do something with the mod as it is probably the most important mod made for this game.

Thank you!

**Comment by gingajamie** [comment]
You can find a fixed version (2.18.0) on my github.

https://github.com/gingajamie/smapi-better-sprinklers-plus-encore/releases/tag/2.18.0

Let me know if any issues.

**Comment by dpraptor** [comment]
Thank you!!
