### ISSUE TITLE
Smapi errors / Please have a look

### ISSUE THREAD

**Issue by myshinobin** [jamescodesthings/smapi-better-sprinklers#5]
Hi, we be running a coop 1.6. experience with 3 players and everything working so far.
Just the sprinklers won do it, using the newest version of Nexus (same as here).
Smap giving a lot of errors. While the sprinkler-size gets visibly saved, the sprinkler itself waters only original.

[Better Sprinklers Plus] Running sprinklers
[Better Sprinklers Plus] This mod failed in the GameLoop.DayStarted event. Technical details:
Failed loading type 'StardewValley.Locations.BuildableGameLocation': TypeLoadException: Could not load type 'StardewValley.Locations.BuildableGameLocation' from assembly 'Stardew Valley, Version=1.6.3.24087, Culture=neutral, PublicKeyToken=null'.
   at BetterSprinklersPlus.Framework.Helpers.LocationHelper.GetAllBuildableLocations()
   at BetterSprinklersPlus.BetterSprinklersPlus.UnwaterAll() in /plugin/BetterSprinklersPlus/BetterSprinklersPlus.cs:line 265
   at BetterSprinklersPlus.BetterSprinklersPlus.RunSprinklers() in /plugin/BetterSprinklersPlus/BetterSprinklersPlus.cs:line 182
   at BetterSprinklersPlus.BetterSprinklersPlus.OnDayStarted(Object sender, DayStartedEventArgs e) in /plugin/BetterSprinklersPlus/BetterSprinklersPlus.cs:line 82
   at StardewModdingAPI.Framework.Events.ManagedEvent`1.Raise(TEventArgs args) in SMAPI\Framework\Events\ManagedEvent.cs:line 101

**Comment by myshinobin** [comment]
Ok, have to add i found out i need to enable them buy paying mones.
Still: The errors come as described and is it normal that my coop partner do not see when i use the sprinklers?
Will the watered crops - they dont see the water sadly - still be watered correctly for all of us on the next day?

**Comment by myshinobin** [comment]
Also now we got the better (2nd) sprinkler, and i cannot set it up on the edit page.
Left side only show 3 bush-signs, and on the right i can only edit the first sprinkler.

**Comment by jamescodesthings** [comment]
Hey, just checking in. I'm sorry, but the mod has no multiplayer support and would take considerable effort to rewrite for multiplayer. It's not something I'm likely to get done. Expect weird behavior.

I'll leave this issue open as a marker to any other devs who have the time.
